# Generated by Django 2.2.4 on 2020-04-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0004_trip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
