# Generated by Django 2.2.4 on 2020-04-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0005_auto_20200427_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
